import { createHash, randomUUID } from "node:crypto";
import { existsSync, lstatSync, mkdirSync, realpathSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve, sep } from "node:path";
import { extractGitHubPullRequestUrl, parseGitHubPullRequestUrl } from "../_shared/github";
import { diffAnchors as indexDiffAnchors } from "./diff-index";
import {
  validatePlanShape,
  type ChangedFile,
  type Finding,
  type ReviewMetadata,
  type ReviewPlan,
  type ReviewResult,
} from "./schema";
export {
  Attention,
  Impact,
  REVIEW_COMMANDS,
  ReviewEvent,
  Severity,
  Side,
  validatePlanShape,
  validateReviewShape,
  type AnchorSide,
  type ChangedFile,
  type Finding,
  type PlanCohort,
  type PlanFile,
  type PostAttempt,
  type ReviewMetadata,
  type ReviewPlan,
  type ReviewResult,
  type ReviewSnapshot,
  type ReviewState,
} from "./schema";

export {
  changedLineAnchors,
  diffAnchors,
  diffHunkRanges,
  parseChangedFilesFromDiff,
  parseDiffGitPath,
  parseGitPathList,
  parsePatchFilePath,
  type DiffHunkRange,
} from "./diff-index";
export const REVIEW_ENTRY_TYPE = "pr-review" as const;
export const Disclosure = "Generated by AI. Please verify before relying on this review.";
export function extractPrUrl(text: string): string | undefined {
  return extractGitHubPullRequestUrl(text);
}
export function parsePrUrl(url: string): Pick<ReviewMetadata, "owner" | "repo" | "number" | "url"> {
  const parsed = parseGitHubPullRequestUrl(url);
  if (!parsed) throw new Error("Expected a valid GitHub pull request URL.");
  return parsed;
}
export function sha256(text: string): string {
  return createHash("sha256").update(text).digest("hex");
}
export function reviewIdFromMetadata(
  meta: Pick<ReviewMetadata, "owner" | "repo" | "number" | "headOid">,
): string {
  return `${meta.owner}-${meta.repo}-${meta.number}-${meta.headOid.slice(0, 12)}-${randomUUID().slice(0, 8)}`.replace(
    /[^a-zA-Z0-9_.-]/g,
    "-",
  );
}
export function marker(reviewId: string, attemptId: string): string {
  return `<!-- pi-env-pr-review:${reviewId}:${attemptId} -->`;
}

function coverage(
  paths: string[],
  expected: string[],
): { missing: string[]; duplicates: string[]; invented: string[] } {
  const expectedSet = new Set(expected);
  const seen = new Set<string>();
  const duplicates: string[] = [];
  const invented: string[] = [];
  for (const path of paths) {
    if (seen.has(path)) duplicates.push(path);
    seen.add(path);
    if (!expectedSet.has(path)) invented.push(path);
  }
  return { missing: expected.filter((p) => !seen.has(p)), duplicates, invented };
}

function addCoverageIssues(
  issues: string[],
  label: string,
  result: ReturnType<typeof coverage>,
): void {
  const suffix = label === "Files" ? "" : ` ${label.toLowerCase()}`;
  if (result.missing.length) issues.push(`Missing${suffix}: ${result.missing.join(", ")}`);
  if (result.duplicates.length)
    issues.push(`Duplicate${suffix}: ${result.duplicates.join(", ")}`);
  if (result.invented.length)
    issues.push(`Invented${suffix}: ${result.invented.join(", ")}`);
}
function evidenceIssues(plan: ReviewPlan, expected: readonly string[]): string[] {
  const issues: string[] = [];
  const expectedSet = new Set(expected);
  const evidencePathSet = new Set(plan.evidence.map((reference) => reference.path));
  const missing = expected.filter((path) => !evidencePathSet.has(path));
  const invented = [...evidencePathSet].filter((path) => !expectedSet.has(path));
  const identities = plan.evidence.map((reference) =>
    `${reference.kind}\0${reference.path}\0${reference.startLine}\0${reference.endLine}`,
  );
  if (missing.length) issues.push(`Missing evidence: ${missing.join(", ")}`);
  if (invented.length) issues.push(`Unplanned evidence: ${invented.join(", ")}`);
  if (plan.evidence.some((reference) => reference.endLine < reference.startLine))
    issues.push("Evidence contains reversed line ranges.");
  if (new Set(identities).size !== identities.length)
    issues.push("Evidence contains duplicate references.");
  return issues;
}
export function validatePlan(
  plan: ReviewPlan,
  changed: readonly ChangedFile[],
): { ok: boolean; message: string } {
  if (!validatePlanShape(plan)) return { ok: false, message: "Plan is malformed." };
  const expected = changed.map((file) => file.path);
  const issues: string[] = [];
  addCoverageIssues(issues, "Files", coverage(plan.files.map((file) => file.path), expected));
  addCoverageIssues(
    issues,
    "Cohorts",
    coverage(plan.cohorts.flatMap((cohort) => cohort.paths), expected),
  );
  issues.push(...evidenceIssues(plan, expected));
  if (issues.length === 0) return { ok: true, message: "Plan accepted." };
  return {
    ok: false,
    message: [
      "Plan must cover each changed path exactly once and include valid evidence for each path.",
      ...issues,
    ].join("\n"),
  };
}

export function validateFindingAnchors(result: ReviewResult, diff: string): ReviewResult {
  const anchors = indexDiffAnchors(diff);
  let next = 1;
  return {
    ...result,
    findings: result.findings.map((f) => {
      const id = `F${next++}`;
      const selected =
        f.impact.toLowerCase() === "high" ||
        ["blocking", "serious"].includes(f.severity.toLowerCase());
      const side = f.side;
      const valid = !!(f.file && f.line && side && anchors.get(f.file)?.[side]?.has(f.line));
      return valid
        ? { ...f, id, selected, anchorValid: true }
        : { ...f, id, line: undefined, side: undefined, selected, anchorValid: false };
    }),
  };
}

export function confined(root: string, requested = "."): string {
  const base = realpathSync(root);
  const target = resolve(base, requested);
  const relFromBase = relative(base, target);
  if (
    relFromBase.startsWith("..") ||
    relFromBase === ".." ||
    relFromBase.includes(`${sep}..${sep}`) ||
    resolve(requested) === requested
  )
    throw new Error("Path traversal is not allowed.");
  const parent = existsSync(target) ? target : dirname(target);
  const parentReal = realpathSync(parent);
  if (!parentReal.startsWith(base + sep) && parentReal !== base)
    throw new Error("Path escapes review worktree.");
  if (existsSync(target)) {
    const real = realpathSync(target);
    if (!real.startsWith(base + sep) && real !== base)
      throw new Error("Symlink escapes review worktree.");
    if (lstatSync(target).isSymbolicLink() && real !== target) {
      /* containment checked */
    }
  }
  return target;
}
export function assertContainedResolved(root: string, target: string): void {
  const base = realpathSync(root);
  const actual = realpathSync(target);
  const rel = relative(base, actual);
  if (rel === ".." || rel.startsWith(`..${sep}`) || resolve(target) !== actual)
    throw new Error("Managed path escapes review storage.");
}
export function bound(text: string, max = 12000): string {
  return text.length > max ? `${text.slice(0, max)}\n[truncated ${text.length - max} chars]` : text;
}
export function persistJson(path: string, value: unknown): void {
  mkdirSync(dirname(path), { recursive: true, mode: 0o700 });
  writeFileSync(path, `${JSON.stringify(value, null, 2)}\n`, { mode: 0o600 });
}
