import { createHash, randomUUID } from "node:crypto";
import { existsSync, lstatSync, mkdirSync, realpathSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve, sep } from "node:path";
import { extractGitHubPullRequestUrl, parseGitHubPullRequestUrl } from "../_shared/github";
import {
  validatePlanShape,
  type ChangedFile,
  type Finding,
  type ReviewMetadata,
  type ReviewPlan,
  type ReviewResult,
} from "./schema";
export {
  Attention,
  Impact,
  REVIEW_COMMANDS,
  ReviewEvent,
  Severity,
  Side,
  validatePlanShape,
  validateReviewShape,
  type AnchorSide,
  type ChangedFile,
  type Finding,
  type PlanCohort,
  type PlanFile,
  type PostAttempt,
  type ReviewMetadata,
  type ReviewPlan,
  type ReviewResult,
  type ReviewSnapshot,
  type ReviewState,
} from "./schema";

export const REVIEW_ENTRY_TYPE = "pr-review" as const;
export const Disclosure = "Generated by AI. Please verify before relying on this review.";
export function extractPrUrl(text: string): string | undefined {
  return extractGitHubPullRequestUrl(text);
}
export function parsePrUrl(url: string): Pick<ReviewMetadata, "owner" | "repo" | "number" | "url"> {
  const parsed = parseGitHubPullRequestUrl(url);
  if (!parsed) throw new Error("Expected a valid GitHub pull request URL.");
  return parsed;
}
export function sha256(text: string): string {
  return createHash("sha256").update(text).digest("hex");
}
export function makeReviewId(
  meta: Pick<ReviewMetadata, "owner" | "repo" | "number" | "headOid">,
): string {
  return `${meta.owner}-${meta.repo}-${meta.number}-${meta.headOid.slice(0, 12)}-${randomUUID().slice(0, 8)}`.replace(
    /[^a-zA-Z0-9_.-]/g,
    "-",
  );
}
export function marker(reviewId: string, attemptId: string): string {
  return `<!-- pi-env-pr-review:${reviewId}:${attemptId} -->`;
}

function coverage(
  paths: string[],
  expected: string[],
): { missing: string[]; duplicates: string[]; invented: string[] } {
  const expectedSet = new Set(expected);
  const seen = new Set<string>();
  const duplicates: string[] = [];
  const invented: string[] = [];
  for (const path of paths) {
    if (seen.has(path)) duplicates.push(path);
    seen.add(path);
    if (!expectedSet.has(path)) invented.push(path);
  }
  return { missing: expected.filter((p) => !seen.has(p)), duplicates, invented };
}

function addCoverageIssues(
  issues: string[],
  label: string,
  result: ReturnType<typeof coverage>,
): void {
  const suffix = label === "Files" ? "" : ` ${label.toLowerCase()}`;
  if (result.missing.length) issues.push(`Missing${suffix}: ${result.missing.join(", ")}`);
  if (result.duplicates.length)
    issues.push(`Duplicate${suffix}: ${result.duplicates.join(", ")}`);
  if (result.invented.length)
    issues.push(`Invented${suffix}: ${result.invented.join(", ")}`);
}
function evidenceIssues(plan: ReviewPlan, expected: readonly string[]): string[] {
  const issues: string[] = [];
  const expectedSet = new Set(expected);
  const evidencePathSet = new Set(plan.evidence.map((reference) => reference.path));
  const missing = expected.filter((path) => !evidencePathSet.has(path));
  const invented = [...evidencePathSet].filter((path) => !expectedSet.has(path));
  const identities = plan.evidence.map((reference) =>
    `${reference.kind}\0${reference.path}\0${reference.startLine}\0${reference.endLine}`,
  );
  if (missing.length) issues.push(`Missing evidence: ${missing.join(", ")}`);
  if (invented.length) issues.push(`Unplanned evidence: ${invented.join(", ")}`);
  if (plan.evidence.some((reference) => reference.endLine < reference.startLine))
    issues.push("Evidence contains reversed line ranges.");
  if (new Set(identities).size !== identities.length)
    issues.push("Evidence contains duplicate references.");
  return issues;
}
export function validatePlan(
  plan: ReviewPlan,
  changed: readonly ChangedFile[],
): { ok: boolean; message: string } {
  if (!validatePlanShape(plan)) return { ok: false, message: "Plan is malformed." };
  const expected = changed.map((file) => file.path);
  const issues: string[] = [];
  addCoverageIssues(issues, "Files", coverage(plan.files.map((file) => file.path), expected));
  addCoverageIssues(
    issues,
    "Cohorts",
    coverage(plan.cohorts.flatMap((cohort) => cohort.paths), expected),
  );
  issues.push(...evidenceIssues(plan, expected));
  if (issues.length === 0) return { ok: true, message: "Plan accepted." };
  return {
    ok: false,
    message: [
      "Plan must cover each changed path exactly once and include valid evidence for each path.",
      ...issues,
    ].join("\n"),
  };
}

function decodeGitQuotedPath(path: string): string {
  const bytes: number[] = [];
  for (let i = 1; i < path.length - 1; i += 1) {
    const ch = path[i];
    if (ch !== "\\") {
      bytes.push(ch.charCodeAt(0));
      continue;
    }
    const next = path[++i];
    if (next === undefined) throw new Error("Invalid Git quoted path.");
    if (/[0-7]/.test(next)) {
      let octal = next;
      for (let n = 0; n < 2 && /[0-7]/.test(path[i + 1] ?? ""); n += 1) octal += path[++i];
      bytes.push(Number.parseInt(octal, 8));
      continue;
    }
    const escapes: Record<string, number> = {
      "\\": 0x5c,
      '"': 0x22,
      n: 0x0a,
      t: 0x09,
      r: 0x0d,
      b: 0x08,
      f: 0x0c,
      v: 0x0b,
      a: 0x07,
    };
    bytes.push(escapes[next] ?? next.charCodeAt(0));
  }
  return Buffer.from(bytes).toString("utf8");
}

function quotedGitPathEnd(text: string, start: number): number {
  let escaped = false;
  for (let index = start + 1; index < text.length; index += 1) {
    const ch = text[index];
    if (escaped) {
      escaped = false;
      continue;
    }
    if (ch === "\\") {
      escaped = true;
      continue;
    }
    if (ch === '"') return index;
  }
  throw new Error("Unterminated Git quoted path.");
}

function decodeGitPath(path: string): string {
  return path.startsWith('"') ? decodeGitQuotedPath(path) : path;
}

export function parseGitPathList(text: string): string[] {
  const paths: string[] = [];
  let index = 0;
  while (index < text.length) {
    while (text[index] === " " || text[index] === "\t") index += 1;
    if (index >= text.length) break;
    if (text[index] === '"') {
      const end = quotedGitPathEnd(text, index);
      paths.push(decodeGitPath(text.slice(index, end + 1)));
      index = end + 1;
      if (index < text.length && text[index] !== " " && text[index] !== "\t")
        throw new Error("Invalid Git path separator.");
      continue;
    }
    const start = index;
    while (index < text.length && text[index] !== " " && text[index] !== "\t") index += 1;
    paths.push(text.slice(start, index));
  }
  return paths;
}

function stripGitPrefix(path: string, prefix: "a" | "b"): string | undefined {
  if (path === "/dev/null") return undefined;
  return path.startsWith(`${prefix}/`) ? path.slice(2) : undefined;
}
export function parseDiffGitPath(line: string): string | undefined {
  if (!line.startsWith("diff --git ")) return undefined;
  const rest = line.slice("diff --git ".length);
  if (!rest.startsWith('"') && rest.startsWith("a/")) {
    for (
      let separator = rest.indexOf(" b/");
      separator >= 0;
      separator = rest.indexOf(" b/", separator + 1)
    ) {
      const oldPath = rest.slice(2, separator);
      const newPath = rest.slice(separator + 3);
      if (oldPath === newPath) return newPath;
    }
    const separator = rest.indexOf(" b/");
    if (separator >= 0) return rest.slice(separator + 3);
  }
  const parts = parseGitPathList(rest);
  if (parts.length !== 2) return undefined;
  return stripGitPrefix(parts[1], "b");
}
export function parsePatchFilePath(line: string): string | undefined {
  const match = line.match(/^(---|\+\+\+) (.+?)(?:\t.*)?$/);
  if (!match) return undefined;
  const path = match[2].startsWith('"') ? parseGitPathList(match[2]).at(0) : match[2];
  return stripGitPrefix(path ?? "", match[1] === "---" ? "a" : "b");
}
export interface DiffHunkRange {
  readonly startLine: number;
  readonly endLine: number;
  readonly header: string;
}
export function diffHunkRanges(section: string): DiffHunkRange[] {
  const lines = section.split(/\r?\n/u);
  if (lines.at(-1) === "") lines.pop();
  const starts = lines.flatMap((line, index) =>
    line.startsWith("@@ ") ? [{ startLine: index + 1, header: line }] : [],
  );
  return starts.map((hunk, index) => ({
    ...hunk,
    endLine: (starts[index + 1]?.startLine ?? lines.length + 1) - 1,
  }));
}
function ensureAnchorFile(
  anchors: Map<string, { LEFT: Set<number>; RIGHT: Set<number> }>,
  file: string,
): void {
  if (!anchors.has(file)) anchors.set(file, { LEFT: new Set(), RIGHT: new Set() });
}

function addDiffLineAnchors(
  line: string,
  set: { LEFT: Set<number>; RIGHT: Set<number> },
  oldLine: number,
  newLine: number,
): { oldLine: number; newLine: number } {
  if (line.startsWith("+")) {
    set.RIGHT.add(newLine);
    return { oldLine, newLine: newLine + 1 };
  }
  if (line.startsWith("-")) {
    set.LEFT.add(oldLine);
    return { oldLine: oldLine + 1, newLine };
  }
  if (line.startsWith(" ")) {
    set.RIGHT.add(newLine);
    set.LEFT.add(oldLine);
    return { oldLine: oldLine + 1, newLine: newLine + 1 };
  }
  return { oldLine, newLine };
}

export function diffAnchors(diff: string): Map<string, { LEFT: Set<number>; RIGHT: Set<number> }> {
  const anchors = new Map<string, { LEFT: Set<number>; RIGHT: Set<number> }>();
  let file = "";
  let oldLine = 0;
  let newLine = 0;
  for (const line of diff.split(/\r?\n/)) {
    const nextFile = parseDiffGitPath(line) ?? parsePatchFilePath(line);
    if (nextFile) {
      file = nextFile;
      ensureAnchorFile(anchors, file);
      continue;
    }
    const hunk = line.match(/^@@ -(\d+)(?:,\d+)? \+(\d+)(?:,\d+)? @@/);
    if (hunk) {
      oldLine = Number(hunk[1]);
      newLine = Number(hunk[2]);
      continue;
    }
    const set = file ? anchors.get(file) : undefined;
    if (!set || line.startsWith("---") || line.startsWith("diff --git")) continue;
    ({ oldLine, newLine } = addDiffLineAnchors(line, set, oldLine, newLine));
  }
  return anchors;
}
export function changedLineAnchors(diff: string): Map<string, Set<number>> {
  const both = diffAnchors(diff);
  return new Map([...both.entries()].map(([p, s]) => [p, s.RIGHT]));
}
export function parseChangedFilesFromDiff(diff: string): ChangedFile[] {
  const paths: ChangedFile[] = [];
  for (const line of diff.split(/\r?\n/)) {
    const p = parseDiffGitPath(line);
    if (p) paths.push({ path: p });
  }
  return paths;
}
export function validateFindingAnchors(result: ReviewResult, diff: string): ReviewResult {
  const anchors = diffAnchors(diff);
  let next = 1;
  return {
    ...result,
    findings: result.findings.map((f) => {
      const id = `F${next++}`;
      const selected =
        f.impact.toLowerCase() === "high" ||
        ["blocking", "serious"].includes(f.severity.toLowerCase());
      const side = f.side;
      const valid = !!(f.file && f.line && side && anchors.get(f.file)?.[side]?.has(f.line));
      return valid
        ? { ...f, id, selected, anchorValid: true }
        : { ...f, id, line: undefined, side: undefined, selected, anchorValid: false };
    }),
  };
}

export function confined(root: string, requested = "."): string {
  const base = realpathSync(root);
  const target = resolve(base, requested);
  const relFromBase = relative(base, target);
  if (
    relFromBase.startsWith("..") ||
    relFromBase === ".." ||
    relFromBase.includes(`${sep}..${sep}`) ||
    resolve(requested) === requested
  )
    throw new Error("Path traversal is not allowed.");
  const parent = existsSync(target) ? target : dirname(target);
  const parentReal = realpathSync(parent);
  if (!parentReal.startsWith(base + sep) && parentReal !== base)
    throw new Error("Path escapes review worktree.");
  if (existsSync(target)) {
    const real = realpathSync(target);
    if (!real.startsWith(base + sep) && real !== base)
      throw new Error("Symlink escapes review worktree.");
    if (lstatSync(target).isSymbolicLink() && real !== target) {
      /* containment checked */
    }
  }
  return target;
}
export function assertContainedResolved(root: string, target: string): void {
  const base = realpathSync(root);
  const actual = realpathSync(target);
  const rel = relative(base, actual);
  if (rel === ".." || rel.startsWith(`..${sep}`) || resolve(target) !== actual)
    throw new Error("Managed path escapes review storage.");
}
export function bound(text: string, max = 12000): string {
  return text.length > max ? `${text.slice(0, max)}\n[truncated ${text.length - max} chars]` : text;
}
export function persistJson(path: string, value: unknown): void {
  mkdirSync(dirname(path), { recursive: true, mode: 0o700 });
  writeFileSync(path, `${JSON.stringify(value, null, 2)}\n`, { mode: 0o600 });
}
