export const LSP_INIT_TIMEOUT_MS = 10_000;
export const LSP_REQUEST_TIMEOUT_MS = 5_000;
export const LSP_SEMANTIC_REQUEST_TIMEOUT_MS = 20_000;

const CLIENT_RESPONSE_OVERHEAD_MS = 5_000;

export const CLIENT_REQUEST_TIMEOUT_MS =
  LSP_INIT_TIMEOUT_MS + LSP_SEMANTIC_REQUEST_TIMEOUT_MS + CLIENT_RESPONSE_OVERHEAD_MS;
