import { createHash, randomUUID } from "node:crypto";
import { existsSync, lstatSync, mkdirSync, realpathSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve, sep } from "node:path";
import {
  validatePlanShape,
  type ChangedFile,
  type Finding,
  type ReviewMetadata,
  type ReviewPlan,
  type ReviewResult,
} from "./schema";
export {
  Attention,
  Impact,
  REVIEW_COMMANDS,
  REVIEW_TOOL_NAMES,
  ReviewEvent,
  Severity,
  Side,
  validatePlanShape,
  validateReviewShape,
  type AnchorSide,
  type ChangedFile,
  type Finding,
  type PlanCohort,
  type PlanFile,
  type PostAttempt,
  type ReviewMetadata,
  type ReviewPlan,
  type ReviewResult,
  type ReviewSnapshot,
  type ReviewState,
} from "./schema";

export const REVIEW_ENTRY_TYPE = "pr-review" as const;
export const Disclosure = "Generated by AI. Please verify before relying on this review.";
const githubName = "[A-Za-z0-9](?:[A-Za-z0-9._-]{0,98}[A-Za-z0-9])?";
const prUrlPattern = new RegExp(
  `^https://github\\.com/(${githubName})/(${githubName})/pull/([1-9][0-9]{0,9})(?:[/?#].*)?$`,
);
export function extractPrUrl(text: string): string | undefined {
  return text.match(
    new RegExp(`https://github\\.com/${githubName}/${githubName}/pull/[1-9][0-9]{0,9}`),
  )?.[0];
}
export function parsePrUrl(url: string): Pick<ReviewMetadata, "owner" | "repo" | "number" | "url"> {
  const m = url.match(prUrlPattern);
  if (!m) throw new Error("Expected a valid GitHub pull request URL.");
  const number = Number(m[3]);
  if (!Number.isSafeInteger(number) || number < 1) throw new Error("Invalid pull request number.");
  return {
    owner: m[1]!,
    repo: m[2]!,
    number,
    url: `https://github.com/${m[1]}/${m[2]}/pull/${m[3]}`,
  };
}
export function sha256(text: string): string {
  return createHash("sha256").update(text).digest("hex");
}
export function makeReviewId(
  meta: Pick<ReviewMetadata, "owner" | "repo" | "number" | "headOid">,
): string {
  return `${meta.owner}-${meta.repo}-${meta.number}-${meta.headOid.slice(0, 12)}-${randomUUID().slice(0, 8)}`.replace(
    /[^a-zA-Z0-9_.-]/g,
    "-",
  );
}
export function marker(reviewId: string, attemptId: string): string {
  return `<!-- pi-env-pr-review:${reviewId}:${attemptId} -->`;
}

function coverage(
  paths: string[],
  expected: string[],
): { missing: string[]; duplicates: string[]; invented: string[] } {
  const expectedSet = new Set(expected);
  const seen = new Set<string>();
  const duplicates: string[] = [];
  const invented: string[] = [];
  for (const path of paths) {
    if (seen.has(path)) duplicates.push(path);
    seen.add(path);
    if (!expectedSet.has(path)) invented.push(path);
  }
  return { missing: expected.filter((p) => !seen.has(p)), duplicates, invented };
}

export function validatePlan(
  plan: ReviewPlan,
  changed: readonly ChangedFile[],
): { ok: boolean; message: string } {
  if (!validatePlanShape(plan)) return { ok: false, message: "Plan is malformed." };
  const expected = changed.map((f) => f.path);
  const filePaths = plan.files.map((f) => f.path);
  const cohortPaths = plan.cohorts.flatMap((c) => c.paths);
  const fileCoverage = coverage(filePaths, expected);
  const cohortCoverage = coverage(cohortPaths, expected);
  const bad =
    fileCoverage.missing.length ||
    fileCoverage.duplicates.length ||
    fileCoverage.invented.length ||
    cohortCoverage.missing.length ||
    cohortCoverage.duplicates.length ||
    cohortCoverage.invented.length;
  if (!bad) return { ok: true, message: "Plan accepted." };
  return {
    ok: false,
    message: [
      "Plan must cover each changed path exactly once.",
      fileCoverage.missing.length ? `Missing: ${fileCoverage.missing.join(", ")}` : "",
      fileCoverage.duplicates.length ? `Duplicate: ${fileCoverage.duplicates.join(", ")}` : "",
      fileCoverage.invented.length ? `Invented: ${fileCoverage.invented.join(", ")}` : "",
    ]
      .filter(Boolean)
      .join("\n"),
  };
}

function decodeGitQuotedPath(path: string): string {
  const bytes: number[] = [];
  for (let i = 1; i < path.length - 1; i += 1) {
    const ch = path[i]!;
    if (ch !== "\\") {
      bytes.push(ch.charCodeAt(0));
      continue;
    }
    const next = path[++i];
    if (next === undefined) throw new Error("Invalid Git quoted path.");
    if (/[0-7]/.test(next)) {
      let octal = next;
      for (let n = 0; n < 2 && /[0-7]/.test(path[i + 1] ?? ""); n += 1) octal += path[++i]!;
      bytes.push(Number.parseInt(octal, 8));
      continue;
    }
    const escapes: Record<string, number> = {
      "\\": 0x5c,
      '"': 0x22,
      n: 0x0a,
      t: 0x09,
      r: 0x0d,
      b: 0x08,
      f: 0x0c,
      v: 0x0b,
      a: 0x07,
    };
    bytes.push(escapes[next] ?? next.charCodeAt(0));
  }
  return Buffer.from(bytes).toString("utf8");
}

function quotedGitPathEnd(text: string, start: number): number {
  let escaped = false;
  for (let index = start + 1; index < text.length; index += 1) {
    const ch = text[index]!;
    if (escaped) {
      escaped = false;
      continue;
    }
    if (ch === "\\") {
      escaped = true;
      continue;
    }
    if (ch === '"') return index;
  }
  throw new Error("Unterminated Git quoted path.");
}

function decodeGitPath(path: string): string {
  return path.startsWith('"') ? decodeGitQuotedPath(path) : path;
}

export function parseGitPathList(text: string): string[] {
  const paths: string[] = [];
  let index = 0;
  while (index < text.length) {
    while (text[index] === " " || text[index] === "\t") index += 1;
    if (index >= text.length) break;
    if (text[index] === '"') {
      const end = quotedGitPathEnd(text, index);
      paths.push(decodeGitPath(text.slice(index, end + 1)));
      index = end + 1;
      if (index < text.length && text[index] !== " " && text[index] !== "\t")
        throw new Error("Invalid Git path separator.");
      continue;
    }
    const start = index;
    while (index < text.length && text[index] !== " " && text[index] !== "\t") index += 1;
    paths.push(text.slice(start, index));
  }
  return paths;
}

function stripGitPrefix(path: string, prefix: "a" | "b"): string | undefined {
  if (path === "/dev/null") return undefined;
  return path.startsWith(`${prefix}/`) ? path.slice(2) : undefined;
}
export function parseDiffGitPath(line: string): string | undefined {
  if (!line.startsWith("diff --git ")) return undefined;
  const rest = line.slice("diff --git ".length);
  if (!rest.startsWith('"') && rest.startsWith("a/")) {
    for (
      let separator = rest.indexOf(" b/");
      separator >= 0;
      separator = rest.indexOf(" b/", separator + 1)
    ) {
      const oldPath = rest.slice(2, separator);
      const newPath = rest.slice(separator + 3);
      if (oldPath === newPath) return newPath;
    }
    const separator = rest.indexOf(" b/");
    if (separator >= 0) return rest.slice(separator + 3);
  }
  const parts = parseGitPathList(rest);
  if (parts.length !== 2) return undefined;
  return stripGitPrefix(parts[1]!, "b");
}
export function parsePatchFilePath(line: string): string | undefined {
  const match = line.match(/^(---|\+\+\+) (.+?)(?:\t.*)?$/);
  if (!match) return undefined;
  const path = match[2]!.startsWith('"') ? parseGitPathList(match[2]!).at(0) : match[2];
  return stripGitPrefix(path ?? "", match[1] === "---" ? "a" : "b");
}
function ensureAnchorFile(
  anchors: Map<string, { LEFT: Set<number>; RIGHT: Set<number> }>,
  file: string,
): void {
  if (!anchors.has(file)) anchors.set(file, { LEFT: new Set(), RIGHT: new Set() });
}

function addDiffLineAnchors(
  line: string,
  set: { LEFT: Set<number>; RIGHT: Set<number> },
  oldLine: number,
  newLine: number,
): { oldLine: number; newLine: number } {
  if (line.startsWith("+")) {
    set.RIGHT.add(newLine);
    return { oldLine, newLine: newLine + 1 };
  }
  if (line.startsWith("-")) {
    set.LEFT.add(oldLine);
    return { oldLine: oldLine + 1, newLine };
  }
  if (line.startsWith(" ")) {
    set.RIGHT.add(newLine);
    set.LEFT.add(oldLine);
    return { oldLine: oldLine + 1, newLine: newLine + 1 };
  }
  return { oldLine, newLine };
}

export function diffAnchors(diff: string): Map<string, { LEFT: Set<number>; RIGHT: Set<number> }> {
  const anchors = new Map<string, { LEFT: Set<number>; RIGHT: Set<number> }>();
  let file = "";
  let oldLine = 0;
  let newLine = 0;
  for (const line of diff.split(/\r?\n/)) {
    const nextFile = parseDiffGitPath(line) ?? parsePatchFilePath(line);
    if (nextFile) {
      file = nextFile;
      ensureAnchorFile(anchors, file);
      continue;
    }
    const hunk = line.match(/^@@ -(\d+)(?:,\d+)? \+(\d+)(?:,\d+)? @@/);
    if (hunk) {
      oldLine = Number(hunk[1]);
      newLine = Number(hunk[2]);
      continue;
    }
    const set = file ? anchors.get(file) : undefined;
    if (!set || line.startsWith("---") || line.startsWith("diff --git")) continue;
    ({ oldLine, newLine } = addDiffLineAnchors(line, set, oldLine, newLine));
  }
  return anchors;
}
export function changedLineAnchors(diff: string): Map<string, Set<number>> {
  const both = diffAnchors(diff);
  return new Map([...both.entries()].map(([p, s]) => [p, s.RIGHT]));
}
export function parseChangedFilesFromDiff(diff: string): ChangedFile[] {
  const paths: ChangedFile[] = [];
  for (const line of diff.split(/\r?\n/)) {
    const p = parseDiffGitPath(line);
    if (p) paths.push({ path: p });
  }
  return paths;
}
export function validateFindingAnchors(result: ReviewResult, diff: string): ReviewResult {
  const anchors = diffAnchors(diff);
  let next = 1;
  return {
    ...result,
    findings: result.findings.map((f) => {
      const id = `F${next++}`;
      const selected =
        f.impact.toLowerCase() === "high" ||
        ["blocking", "serious"].includes(f.severity.toLowerCase());
      const side = f.side;
      const valid = !!(f.file && f.line && side && anchors.get(f.file)?.[side]?.has(f.line));
      return valid
        ? { ...f, id, selected, anchorValid: true }
        : { ...f, id, line: undefined, side: undefined, selected, anchorValid: false };
    }),
  };
}

export function confined(root: string, requested = "."): string {
  const base = realpathSync(root);
  const target = resolve(base, requested);
  const relFromBase = relative(base, target);
  if (
    relFromBase.startsWith("..") ||
    relFromBase === ".." ||
    relFromBase.includes(`${sep}..${sep}`) ||
    resolve(requested) === requested
  )
    throw new Error("Path traversal is not allowed.");
  const parent = existsSync(target) ? target : dirname(target);
  const parentReal = realpathSync(parent);
  if (!parentReal.startsWith(base + sep) && parentReal !== base)
    throw new Error("Path escapes review worktree.");
  if (existsSync(target)) {
    const real = realpathSync(target);
    if (!real.startsWith(base + sep) && real !== base)
      throw new Error("Symlink escapes review worktree.");
    if (lstatSync(target).isSymbolicLink() && real !== target) {
      /* containment checked */
    }
  }
  return target;
}
export function assertContainedResolved(root: string, target: string): void {
  const base = realpathSync(root);
  const actual = realpathSync(target);
  const rel = relative(base, actual);
  if (rel === ".." || rel.startsWith(`..${sep}`) || resolve(target) !== actual)
    throw new Error("Managed path escapes review storage.");
}
export function bound(text: string, max = 12000): string {
  return text.length > max ? `${text.slice(0, max)}\n[truncated ${text.length - max} chars]` : text;
}
export function persistJson(path: string, value: unknown): void {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, `${JSON.stringify(value, null, 2)}\n`);
}
